project: my-ci-example

# 测试环境
sit:
  script:
    - echo "Hello"
    - npm install
  only:
    # 匹配分支的正则
    - /^test_.*/ #test_*分支更新时执行上面的script

# release环境
release:
  script:
    - export PATH="/data/node16/bin:$PATH"
    - npm i
    - npm run build
  only:
    - /^release.*/